### ISSUE TITLE
RabbitMQ 3.7 breaking changes

### ISSUE THREAD

**Issue by colinfrei** [webreactor/rmq-dump#5]
I haven't tested it yet, but I ran into a related issue and I'm assuming that this tool will be affected as well.

RabbitMQ 3.7 caused some breaking changes in the management API: https://github.com/rabbitmq/rabbitmq-server/releases/tag/v3.7.0

The issue I came across is that _requeue_ isn't an option anymore, that's now named ackmode and has four different possible values.

**Comment by toecto** [comment]
requeue is not used.
rmq-dump is tested on RabbitMQ 3.7
